// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ventaTickets.Migrations
{
    [DbContext(typeof(ventaTicketsContext))]
    partial class ventaTicketsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ventaTickets.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("numero")
                        .HasColumnType("INTEGER");

                    b.Property<double>("precio")
                        .HasColumnType("REAL");

                    b.Property<string>("sector")
                        .HasColumnType("TEXT");

                    b.Property<int>("showId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ubicacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("showId");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("ventaTickets.Models.Show", b =>
                {
                    b.Property<int>("showId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantCampo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantPlateaAlta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantPlateaBaja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("direccion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("precioCampo")
                        .HasColumnType("REAL");

                    b.Property<int>("precioPlateaAlta")
                        .HasColumnType("INTEGER");

                    b.Property<double>("precioPlateaBaja")
                        .HasColumnType("REAL");

                    b.HasKey("showId");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("ventaTickets.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("administrador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dni")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ventaTickets.Models.Entrada", b =>
                {
                    b.HasOne("ventaTickets.Models.Show", "show")
                        .WithMany("entradas")
                        .HasForeignKey("showId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("show");
                });

            modelBuilder.Entity("ventaTickets.Models.Show", b =>
                {
                    b.Navigation("entradas");
                });
#pragma warning restore 612, 618
        }
    }
}
